[package]
name = "gifconvert"
version = "0.2.0"
edition = "2021"
description = "A utility to convert images to gifs."

[dependencies]
clap = { version = "3.2.8", features = ["derive"] }
gif = "0.11.4"
image = "0.24.2"
